name: alan
description: Pure Dart library to easily integrate with any Cosmos-based chain.
version: 0.40.2+1
homepage: https://github.com/alan-sdk/alan.dart
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  analyzer: ^3.4.1
  asn1lib: ^1.1.0
  bech32: ^0.2.1
  bip39: ^1.0.6
  convert: ^3.0.1
  equatable: ^2.0.3
  fixnum: ^1.0.0
  grpc: ^3.0.2
  hex: ^0.2.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  meta: ^1.7.0
  pointycastle: ^3.5.2
  protobuf: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.8
  mockito: ^5.1.0
  mock_web_server: ^4.1.1
#  pedantic: ^1.11.0
  test: ^1.20.2
